// flow-typed signature: 47152c75021bcf09ef6da8f4794643fc
// flow-typed version: <<STUB>>/classlist.js_vgithub:eligrey/classList.js.git/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'classlist.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'classlist.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'classlist.js/classList' {
  declare module.exports: any;
}

declare module 'classlist.js/classList.min' {
  declare module.exports: any;
}

declare module 'classlist.js/tests/remove' {
  declare module.exports: any;
}

declare module 'classlist.js/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'classlist.js/classList.js' {
  declare module.exports: $Exports<'classlist.js/classList'>;
}
declare module 'classlist.js/classList.min.js' {
  declare module.exports: $Exports<'classlist.js/classList.min'>;
}
declare module 'classlist.js/tests/remove.js' {
  declare module.exports: $Exports<'classlist.js/tests/remove'>;
}
declare module 'classlist.js/tests/tests.js' {
  declare module.exports: $Exports<'classlist.js/tests/tests'>;
}
