// flow-typed signature: c4bbd5f3c72fc85d883e7691f78c673c
// flow-typed version: <<STUB>>/css-toggle-switch_v4.1.x/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-toggle-switch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-toggle-switch' {
  declare module.exports: any;
}
