// flow-typed signature: 934d08e876db0f555dfc6ccb19eed618
// flow-typed version: <<STUB>>/jQuery-ui-Slider-Pips_vgithub:simeydotme/jQuery-ui-Slider-Pips.git/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jQuery-ui-Slider-Pips'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jQuery-ui-Slider-Pips' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jQuery-ui-Slider-Pips/dist/jquery-ui-slider-pips' {
  declare module.exports: any;
}

declare module 'jQuery-ui-Slider-Pips/dist/jquery-ui-slider-pips.min' {
  declare module.exports: any;
}

declare module 'jQuery-ui-Slider-Pips/gulpfile' {
  declare module.exports: any;
}

declare module 'jQuery-ui-Slider-Pips/src/js/jquery-ui-slider-pips' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jQuery-ui-Slider-Pips/dist/jquery-ui-slider-pips.js' {
  declare module.exports: $Exports<'jQuery-ui-Slider-Pips/dist/jquery-ui-slider-pips'>;
}
declare module 'jQuery-ui-Slider-Pips/dist/jquery-ui-slider-pips.min.js' {
  declare module.exports: $Exports<'jQuery-ui-Slider-Pips/dist/jquery-ui-slider-pips.min'>;
}
declare module 'jQuery-ui-Slider-Pips/gulpfile.js' {
  declare module.exports: $Exports<'jQuery-ui-Slider-Pips/gulpfile'>;
}
declare module 'jQuery-ui-Slider-Pips/src/js/jquery-ui-slider-pips.js' {
  declare module.exports: $Exports<'jQuery-ui-Slider-Pips/src/js/jquery-ui-slider-pips'>;
}
