// flow-typed signature: 7c7bf622335b92b55ca01b0088a968b8
// flow-typed version: <<STUB>>/locutus_v2.0.x/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'locutus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'locutus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'locutus/_util/cli' {
  declare module.exports: any;
}

declare module 'locutus/_util/util' {
  declare module.exports: any;
}

declare module 'locutus/c/index' {
  declare module.exports: any;
}

declare module 'locutus/c/math/abs' {
  declare module.exports: any;
}

declare module 'locutus/c/math/frexp' {
  declare module.exports: any;
}

declare module 'locutus/c/math/index' {
  declare module.exports: any;
}

declare module 'locutus/c/stdio/index' {
  declare module.exports: any;
}

declare module 'locutus/c/stdio/sprintf' {
  declare module.exports: any;
}

declare module 'locutus/golang/index' {
  declare module.exports: any;
}

declare module 'locutus/golang/strings/Contains' {
  declare module.exports: any;
}

declare module 'locutus/golang/strings/Count' {
  declare module.exports: any;
}

declare module 'locutus/golang/strings/index' {
  declare module.exports: any;
}

declare module 'locutus/golang/strings/Index2' {
  declare module.exports: any;
}

declare module 'locutus/golang/strings/LastIndex' {
  declare module.exports: any;
}

declare module 'locutus/php/_helpers/_bc' {
  declare module.exports: any;
}

declare module 'locutus/php/_helpers/_php_cast_int' {
  declare module.exports: any;
}

declare module 'locutus/php/_helpers/_phpCastString' {
  declare module.exports: any;
}

declare module 'locutus/php/_helpers/index' {
  declare module.exports: any;
}

declare module 'locutus/php/_locutus_shared/_locutus_shared_bc' {
  declare module.exports: any;
}

declare module 'locutus/php/_locutus_shared/index' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_change_key_case' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_chunk' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_combine' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_count_values' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_diff_assoc' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_diff_key' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_diff_uassoc' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_diff_ukey' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_diff' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_fill_keys' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_fill' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_filter' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_flip' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_intersect_assoc' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_intersect_key' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_intersect_uassoc' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_intersect_ukey' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_intersect' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_key_exists' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_keys' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_map' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_merge_recursive' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_merge' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_multisort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_pad' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_pop' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_product' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_push' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_rand' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_reduce' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_replace_recursive' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_replace' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_reverse' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_search' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_shift' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_slice' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_splice' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_sum' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_udiff_assoc' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_udiff_uassoc' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_udiff' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_uintersect_uassoc' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_uintersect' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_unique' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_unshift' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_values' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_walk_recursive' {
  declare module.exports: any;
}

declare module 'locutus/php/array/array_walk' {
  declare module.exports: any;
}

declare module 'locutus/php/array/arsort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/asort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/count' {
  declare module.exports: any;
}

declare module 'locutus/php/array/current' {
  declare module.exports: any;
}

declare module 'locutus/php/array/each' {
  declare module.exports: any;
}

declare module 'locutus/php/array/end' {
  declare module.exports: any;
}

declare module 'locutus/php/array/in_array' {
  declare module.exports: any;
}

declare module 'locutus/php/array/index' {
  declare module.exports: any;
}

declare module 'locutus/php/array/key' {
  declare module.exports: any;
}

declare module 'locutus/php/array/krsort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/ksort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/natcasesort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/natsort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/next' {
  declare module.exports: any;
}

declare module 'locutus/php/array/pos' {
  declare module.exports: any;
}

declare module 'locutus/php/array/prev' {
  declare module.exports: any;
}

declare module 'locutus/php/array/range' {
  declare module.exports: any;
}

declare module 'locutus/php/array/reset' {
  declare module.exports: any;
}

declare module 'locutus/php/array/rsort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/shuffle' {
  declare module.exports: any;
}

declare module 'locutus/php/array/sizeof' {
  declare module.exports: any;
}

declare module 'locutus/php/array/sort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/uasort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/uksort' {
  declare module.exports: any;
}

declare module 'locutus/php/array/usort' {
  declare module.exports: any;
}

declare module 'locutus/php/bc/bcadd' {
  declare module.exports: any;
}

declare module 'locutus/php/bc/bccomp' {
  declare module.exports: any;
}

declare module 'locutus/php/bc/bcdiv' {
  declare module.exports: any;
}

declare module 'locutus/php/bc/bcmul' {
  declare module.exports: any;
}

declare module 'locutus/php/bc/bcround' {
  declare module.exports: any;
}

declare module 'locutus/php/bc/bcscale' {
  declare module.exports: any;
}

declare module 'locutus/php/bc/bcsub' {
  declare module.exports: any;
}

declare module 'locutus/php/bc/index' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_alnum' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_alpha' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_cntrl' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_digit' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_graph' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_lower' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_print' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_punct' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_space' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_upper' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/ctype_xdigit' {
  declare module.exports: any;
}

declare module 'locutus/php/ctype/index' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/checkdate' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/date_parse' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/date' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/getdate' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/gettimeofday' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/gmdate' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/gmmktime' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/gmstrftime' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/idate' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/index' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/microtime' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/mktime' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/strftime' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/strptime' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/strtotime' {
  declare module.exports: any;
}

declare module 'locutus/php/datetime/time' {
  declare module.exports: any;
}

declare module 'locutus/php/exec/escapeshellarg' {
  declare module.exports: any;
}

declare module 'locutus/php/exec/index' {
  declare module.exports: any;
}

declare module 'locutus/php/filesystem/basename' {
  declare module.exports: any;
}

declare module 'locutus/php/filesystem/dirname' {
  declare module.exports: any;
}

declare module 'locutus/php/filesystem/file_get_contents' {
  declare module.exports: any;
}

declare module 'locutus/php/filesystem/index' {
  declare module.exports: any;
}

declare module 'locutus/php/filesystem/pathinfo' {
  declare module.exports: any;
}

declare module 'locutus/php/filesystem/realpath' {
  declare module.exports: any;
}

declare module 'locutus/php/funchand/call_user_func_array' {
  declare module.exports: any;
}

declare module 'locutus/php/funchand/call_user_func' {
  declare module.exports: any;
}

declare module 'locutus/php/funchand/create_function' {
  declare module.exports: any;
}

declare module 'locutus/php/funchand/function_exists' {
  declare module.exports: any;
}

declare module 'locutus/php/funchand/get_defined_functions' {
  declare module.exports: any;
}

declare module 'locutus/php/funchand/index' {
  declare module.exports: any;
}

declare module 'locutus/php/i18n/i18n_loc_get_default' {
  declare module.exports: any;
}

declare module 'locutus/php/i18n/i18n_loc_set_default' {
  declare module.exports: any;
}

declare module 'locutus/php/i18n/index' {
  declare module.exports: any;
}

declare module 'locutus/php/index' {
  declare module.exports: any;
}

declare module 'locutus/php/info/assert_options' {
  declare module.exports: any;
}

declare module 'locutus/php/info/getenv' {
  declare module.exports: any;
}

declare module 'locutus/php/info/index' {
  declare module.exports: any;
}

declare module 'locutus/php/info/ini_get' {
  declare module.exports: any;
}

declare module 'locutus/php/info/ini_set' {
  declare module.exports: any;
}

declare module 'locutus/php/info/set_time_limit' {
  declare module.exports: any;
}

declare module 'locutus/php/info/version_compare' {
  declare module.exports: any;
}

declare module 'locutus/php/json/index' {
  declare module.exports: any;
}

declare module 'locutus/php/json/json_decode' {
  declare module.exports: any;
}

declare module 'locutus/php/json/json_encode' {
  declare module.exports: any;
}

declare module 'locutus/php/json/json_last_error' {
  declare module.exports: any;
}

declare module 'locutus/php/math/abs' {
  declare module.exports: any;
}

declare module 'locutus/php/math/acos' {
  declare module.exports: any;
}

declare module 'locutus/php/math/acosh' {
  declare module.exports: any;
}

declare module 'locutus/php/math/asin' {
  declare module.exports: any;
}

declare module 'locutus/php/math/asinh' {
  declare module.exports: any;
}

declare module 'locutus/php/math/atan' {
  declare module.exports: any;
}

declare module 'locutus/php/math/atan2' {
  declare module.exports: any;
}

declare module 'locutus/php/math/atanh' {
  declare module.exports: any;
}

declare module 'locutus/php/math/base_convert' {
  declare module.exports: any;
}

declare module 'locutus/php/math/bindec' {
  declare module.exports: any;
}

declare module 'locutus/php/math/ceil' {
  declare module.exports: any;
}

declare module 'locutus/php/math/cos' {
  declare module.exports: any;
}

declare module 'locutus/php/math/cosh' {
  declare module.exports: any;
}

declare module 'locutus/php/math/decbin' {
  declare module.exports: any;
}

declare module 'locutus/php/math/dechex' {
  declare module.exports: any;
}

declare module 'locutus/php/math/decoct' {
  declare module.exports: any;
}

declare module 'locutus/php/math/deg2rad' {
  declare module.exports: any;
}

declare module 'locutus/php/math/exp' {
  declare module.exports: any;
}

declare module 'locutus/php/math/expm1' {
  declare module.exports: any;
}

declare module 'locutus/php/math/floor' {
  declare module.exports: any;
}

declare module 'locutus/php/math/fmod' {
  declare module.exports: any;
}

declare module 'locutus/php/math/getrandmax' {
  declare module.exports: any;
}

declare module 'locutus/php/math/hexdec' {
  declare module.exports: any;
}

declare module 'locutus/php/math/hypot' {
  declare module.exports: any;
}

declare module 'locutus/php/math/index' {
  declare module.exports: any;
}

declare module 'locutus/php/math/is_finite' {
  declare module.exports: any;
}

declare module 'locutus/php/math/is_infinite' {
  declare module.exports: any;
}

declare module 'locutus/php/math/is_nan' {
  declare module.exports: any;
}

declare module 'locutus/php/math/lcg_value' {
  declare module.exports: any;
}

declare module 'locutus/php/math/log' {
  declare module.exports: any;
}

declare module 'locutus/php/math/log10' {
  declare module.exports: any;
}

declare module 'locutus/php/math/log1p' {
  declare module.exports: any;
}

declare module 'locutus/php/math/max' {
  declare module.exports: any;
}

declare module 'locutus/php/math/min' {
  declare module.exports: any;
}

declare module 'locutus/php/math/mt_getrandmax' {
  declare module.exports: any;
}

declare module 'locutus/php/math/mt_rand' {
  declare module.exports: any;
}

declare module 'locutus/php/math/octdec' {
  declare module.exports: any;
}

declare module 'locutus/php/math/pi' {
  declare module.exports: any;
}

declare module 'locutus/php/math/pow' {
  declare module.exports: any;
}

declare module 'locutus/php/math/rad2deg' {
  declare module.exports: any;
}

declare module 'locutus/php/math/rand' {
  declare module.exports: any;
}

declare module 'locutus/php/math/round' {
  declare module.exports: any;
}

declare module 'locutus/php/math/sin' {
  declare module.exports: any;
}

declare module 'locutus/php/math/sinh' {
  declare module.exports: any;
}

declare module 'locutus/php/math/sqrt' {
  declare module.exports: any;
}

declare module 'locutus/php/math/tan' {
  declare module.exports: any;
}

declare module 'locutus/php/math/tanh' {
  declare module.exports: any;
}

declare module 'locutus/php/misc/index' {
  declare module.exports: any;
}

declare module 'locutus/php/misc/pack' {
  declare module.exports: any;
}

declare module 'locutus/php/misc/uniqid' {
  declare module.exports: any;
}

declare module 'locutus/php/net-gopher/gopher_parsedir' {
  declare module.exports: any;
}

declare module 'locutus/php/net-gopher/index' {
  declare module.exports: any;
}

declare module 'locutus/php/network/index' {
  declare module.exports: any;
}

declare module 'locutus/php/network/inet_ntop' {
  declare module.exports: any;
}

declare module 'locutus/php/network/inet_pton' {
  declare module.exports: any;
}

declare module 'locutus/php/network/ip2long' {
  declare module.exports: any;
}

declare module 'locutus/php/network/long2ip' {
  declare module.exports: any;
}

declare module 'locutus/php/network/setcookie' {
  declare module.exports: any;
}

declare module 'locutus/php/network/setrawcookie' {
  declare module.exports: any;
}

declare module 'locutus/php/pcre/index' {
  declare module.exports: any;
}

declare module 'locutus/php/pcre/preg_quote' {
  declare module.exports: any;
}

declare module 'locutus/php/pcre/sql_regcase' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/addcslashes' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/addslashes' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/bin2hex' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/chop' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/chr' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/chunk_split' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/convert_cyr_string' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/convert_uuencode' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/count_chars' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/crc32' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/echo' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/explode' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/get_html_translation_table' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/hex2bin' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/html_entity_decode' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/htmlentities' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/htmlspecialchars_decode' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/htmlspecialchars' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/implode' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/index' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/join' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/lcfirst' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/levenshtein' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/localeconv' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/ltrim' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/md5_file' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/md5' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/metaphone' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/money_format' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/nl_langinfo' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/nl2br' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/number_format' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/ord' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/parse_str' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/printf' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/quoted_printable_decode' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/quoted_printable_encode' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/quotemeta' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/rtrim' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/setlocale' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/sha1_file' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/sha1' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/similar_text' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/soundex' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/split' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/sprintf' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/sscanf' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/str_getcsv' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/str_ireplace' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/str_pad' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/str_repeat' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/str_replace' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/str_rot13' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/str_shuffle' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/str_split' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/str_word_count' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strcasecmp' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strchr' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strcmp' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strcoll' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strcspn' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strip_tags' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/stripos' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/stripslashes' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/stristr' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strlen' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strnatcasecmp' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strnatcmp' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strncasecmp' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strncmp' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strpbrk' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strpos' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strrchr' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strrev' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strripos' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strrpos' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strspn' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strstr' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strtok' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strtolower' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strtoupper' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/strtr' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/substr_compare' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/substr_count' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/substr_replace' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/substr' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/trim' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/ucfirst' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/ucwords' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/vprintf' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/vsprintf' {
  declare module.exports: any;
}

declare module 'locutus/php/strings/wordwrap' {
  declare module.exports: any;
}

declare module 'locutus/php/url/base64_decode' {
  declare module.exports: any;
}

declare module 'locutus/php/url/base64_encode' {
  declare module.exports: any;
}

declare module 'locutus/php/url/http_build_query' {
  declare module.exports: any;
}

declare module 'locutus/php/url/index' {
  declare module.exports: any;
}

declare module 'locutus/php/url/parse_url' {
  declare module.exports: any;
}

declare module 'locutus/php/url/rawurldecode' {
  declare module.exports: any;
}

declare module 'locutus/php/url/rawurlencode' {
  declare module.exports: any;
}

declare module 'locutus/php/url/urldecode' {
  declare module.exports: any;
}

declare module 'locutus/php/url/urlencode' {
  declare module.exports: any;
}

declare module 'locutus/php/var/boolval' {
  declare module.exports: any;
}

declare module 'locutus/php/var/doubleval' {
  declare module.exports: any;
}

declare module 'locutus/php/var/empty' {
  declare module.exports: any;
}

declare module 'locutus/php/var/floatval' {
  declare module.exports: any;
}

declare module 'locutus/php/var/gettype' {
  declare module.exports: any;
}

declare module 'locutus/php/var/index' {
  declare module.exports: any;
}

declare module 'locutus/php/var/intval' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_array' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_binary' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_bool' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_buffer' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_callable' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_double' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_float' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_int' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_integer' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_long' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_null' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_numeric' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_object' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_real' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_scalar' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_string' {
  declare module.exports: any;
}

declare module 'locutus/php/var/is_unicode' {
  declare module.exports: any;
}

declare module 'locutus/php/var/isset' {
  declare module.exports: any;
}

declare module 'locutus/php/var/print_r' {
  declare module.exports: any;
}

declare module 'locutus/php/var/serialize' {
  declare module.exports: any;
}

declare module 'locutus/php/var/strval' {
  declare module.exports: any;
}

declare module 'locutus/php/var/unserialize' {
  declare module.exports: any;
}

declare module 'locutus/php/var/var_dump' {
  declare module.exports: any;
}

declare module 'locutus/php/var/var_export' {
  declare module.exports: any;
}

declare module 'locutus/php/xdiff/index' {
  declare module.exports: any;
}

declare module 'locutus/php/xdiff/xdiff_string_diff' {
  declare module.exports: any;
}

declare module 'locutus/php/xdiff/xdiff_string_patch' {
  declare module.exports: any;
}

declare module 'locutus/php/xml/index' {
  declare module.exports: any;
}

declare module 'locutus/php/xml/utf8_decode' {
  declare module.exports: any;
}

declare module 'locutus/php/xml/utf8_encode' {
  declare module.exports: any;
}

declare module 'locutus/python/index' {
  declare module.exports: any;
}

declare module 'locutus/python/string/capwords' {
  declare module.exports: any;
}

declare module 'locutus/python/string/index' {
  declare module.exports: any;
}

declare module 'locutus/ruby/index' {
  declare module.exports: any;
}

declare module 'locutus/ruby/Math/acos' {
  declare module.exports: any;
}

declare module 'locutus/ruby/Math/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'locutus/_util/cli.js' {
  declare module.exports: $Exports<'locutus/_util/cli'>;
}
declare module 'locutus/_util/util.js' {
  declare module.exports: $Exports<'locutus/_util/util'>;
}
declare module 'locutus/c/index.js' {
  declare module.exports: $Exports<'locutus/c/index'>;
}
declare module 'locutus/c/math/abs.js' {
  declare module.exports: $Exports<'locutus/c/math/abs'>;
}
declare module 'locutus/c/math/frexp.js' {
  declare module.exports: $Exports<'locutus/c/math/frexp'>;
}
declare module 'locutus/c/math/index.js' {
  declare module.exports: $Exports<'locutus/c/math/index'>;
}
declare module 'locutus/c/stdio/index.js' {
  declare module.exports: $Exports<'locutus/c/stdio/index'>;
}
declare module 'locutus/c/stdio/sprintf.js' {
  declare module.exports: $Exports<'locutus/c/stdio/sprintf'>;
}
declare module 'locutus/golang/index.js' {
  declare module.exports: $Exports<'locutus/golang/index'>;
}
declare module 'locutus/golang/strings/Contains.js' {
  declare module.exports: $Exports<'locutus/golang/strings/Contains'>;
}
declare module 'locutus/golang/strings/Count.js' {
  declare module.exports: $Exports<'locutus/golang/strings/Count'>;
}
declare module 'locutus/golang/strings/index.js' {
  declare module.exports: $Exports<'locutus/golang/strings/index'>;
}
declare module 'locutus/golang/strings/Index2.js' {
  declare module.exports: $Exports<'locutus/golang/strings/Index2'>;
}
declare module 'locutus/golang/strings/LastIndex.js' {
  declare module.exports: $Exports<'locutus/golang/strings/LastIndex'>;
}
declare module 'locutus/index' {
  declare module.exports: $Exports<'locutus'>;
}
declare module 'locutus/index.js' {
  declare module.exports: $Exports<'locutus'>;
}
declare module 'locutus/php/_helpers/_bc.js' {
  declare module.exports: $Exports<'locutus/php/_helpers/_bc'>;
}
declare module 'locutus/php/_helpers/_php_cast_int.js' {
  declare module.exports: $Exports<'locutus/php/_helpers/_php_cast_int'>;
}
declare module 'locutus/php/_helpers/_phpCastString.js' {
  declare module.exports: $Exports<'locutus/php/_helpers/_phpCastString'>;
}
declare module 'locutus/php/_helpers/index.js' {
  declare module.exports: $Exports<'locutus/php/_helpers/index'>;
}
declare module 'locutus/php/_locutus_shared/_locutus_shared_bc.js' {
  declare module.exports: $Exports<'locutus/php/_locutus_shared/_locutus_shared_bc'>;
}
declare module 'locutus/php/_locutus_shared/index.js' {
  declare module.exports: $Exports<'locutus/php/_locutus_shared/index'>;
}
declare module 'locutus/php/array/array_change_key_case.js' {
  declare module.exports: $Exports<'locutus/php/array/array_change_key_case'>;
}
declare module 'locutus/php/array/array_chunk.js' {
  declare module.exports: $Exports<'locutus/php/array/array_chunk'>;
}
declare module 'locutus/php/array/array_combine.js' {
  declare module.exports: $Exports<'locutus/php/array/array_combine'>;
}
declare module 'locutus/php/array/array_count_values.js' {
  declare module.exports: $Exports<'locutus/php/array/array_count_values'>;
}
declare module 'locutus/php/array/array_diff_assoc.js' {
  declare module.exports: $Exports<'locutus/php/array/array_diff_assoc'>;
}
declare module 'locutus/php/array/array_diff_key.js' {
  declare module.exports: $Exports<'locutus/php/array/array_diff_key'>;
}
declare module 'locutus/php/array/array_diff_uassoc.js' {
  declare module.exports: $Exports<'locutus/php/array/array_diff_uassoc'>;
}
declare module 'locutus/php/array/array_diff_ukey.js' {
  declare module.exports: $Exports<'locutus/php/array/array_diff_ukey'>;
}
declare module 'locutus/php/array/array_diff.js' {
  declare module.exports: $Exports<'locutus/php/array/array_diff'>;
}
declare module 'locutus/php/array/array_fill_keys.js' {
  declare module.exports: $Exports<'locutus/php/array/array_fill_keys'>;
}
declare module 'locutus/php/array/array_fill.js' {
  declare module.exports: $Exports<'locutus/php/array/array_fill'>;
}
declare module 'locutus/php/array/array_filter.js' {
  declare module.exports: $Exports<'locutus/php/array/array_filter'>;
}
declare module 'locutus/php/array/array_flip.js' {
  declare module.exports: $Exports<'locutus/php/array/array_flip'>;
}
declare module 'locutus/php/array/array_intersect_assoc.js' {
  declare module.exports: $Exports<'locutus/php/array/array_intersect_assoc'>;
}
declare module 'locutus/php/array/array_intersect_key.js' {
  declare module.exports: $Exports<'locutus/php/array/array_intersect_key'>;
}
declare module 'locutus/php/array/array_intersect_uassoc.js' {
  declare module.exports: $Exports<'locutus/php/array/array_intersect_uassoc'>;
}
declare module 'locutus/php/array/array_intersect_ukey.js' {
  declare module.exports: $Exports<'locutus/php/array/array_intersect_ukey'>;
}
declare module 'locutus/php/array/array_intersect.js' {
  declare module.exports: $Exports<'locutus/php/array/array_intersect'>;
}
declare module 'locutus/php/array/array_key_exists.js' {
  declare module.exports: $Exports<'locutus/php/array/array_key_exists'>;
}
declare module 'locutus/php/array/array_keys.js' {
  declare module.exports: $Exports<'locutus/php/array/array_keys'>;
}
declare module 'locutus/php/array/array_map.js' {
  declare module.exports: $Exports<'locutus/php/array/array_map'>;
}
declare module 'locutus/php/array/array_merge_recursive.js' {
  declare module.exports: $Exports<'locutus/php/array/array_merge_recursive'>;
}
declare module 'locutus/php/array/array_merge.js' {
  declare module.exports: $Exports<'locutus/php/array/array_merge'>;
}
declare module 'locutus/php/array/array_multisort.js' {
  declare module.exports: $Exports<'locutus/php/array/array_multisort'>;
}
declare module 'locutus/php/array/array_pad.js' {
  declare module.exports: $Exports<'locutus/php/array/array_pad'>;
}
declare module 'locutus/php/array/array_pop.js' {
  declare module.exports: $Exports<'locutus/php/array/array_pop'>;
}
declare module 'locutus/php/array/array_product.js' {
  declare module.exports: $Exports<'locutus/php/array/array_product'>;
}
declare module 'locutus/php/array/array_push.js' {
  declare module.exports: $Exports<'locutus/php/array/array_push'>;
}
declare module 'locutus/php/array/array_rand.js' {
  declare module.exports: $Exports<'locutus/php/array/array_rand'>;
}
declare module 'locutus/php/array/array_reduce.js' {
  declare module.exports: $Exports<'locutus/php/array/array_reduce'>;
}
declare module 'locutus/php/array/array_replace_recursive.js' {
  declare module.exports: $Exports<'locutus/php/array/array_replace_recursive'>;
}
declare module 'locutus/php/array/array_replace.js' {
  declare module.exports: $Exports<'locutus/php/array/array_replace'>;
}
declare module 'locutus/php/array/array_reverse.js' {
  declare module.exports: $Exports<'locutus/php/array/array_reverse'>;
}
declare module 'locutus/php/array/array_search.js' {
  declare module.exports: $Exports<'locutus/php/array/array_search'>;
}
declare module 'locutus/php/array/array_shift.js' {
  declare module.exports: $Exports<'locutus/php/array/array_shift'>;
}
declare module 'locutus/php/array/array_slice.js' {
  declare module.exports: $Exports<'locutus/php/array/array_slice'>;
}
declare module 'locutus/php/array/array_splice.js' {
  declare module.exports: $Exports<'locutus/php/array/array_splice'>;
}
declare module 'locutus/php/array/array_sum.js' {
  declare module.exports: $Exports<'locutus/php/array/array_sum'>;
}
declare module 'locutus/php/array/array_udiff_assoc.js' {
  declare module.exports: $Exports<'locutus/php/array/array_udiff_assoc'>;
}
declare module 'locutus/php/array/array_udiff_uassoc.js' {
  declare module.exports: $Exports<'locutus/php/array/array_udiff_uassoc'>;
}
declare module 'locutus/php/array/array_udiff.js' {
  declare module.exports: $Exports<'locutus/php/array/array_udiff'>;
}
declare module 'locutus/php/array/array_uintersect_uassoc.js' {
  declare module.exports: $Exports<'locutus/php/array/array_uintersect_uassoc'>;
}
declare module 'locutus/php/array/array_uintersect.js' {
  declare module.exports: $Exports<'locutus/php/array/array_uintersect'>;
}
declare module 'locutus/php/array/array_unique.js' {
  declare module.exports: $Exports<'locutus/php/array/array_unique'>;
}
declare module 'locutus/php/array/array_unshift.js' {
  declare module.exports: $Exports<'locutus/php/array/array_unshift'>;
}
declare module 'locutus/php/array/array_values.js' {
  declare module.exports: $Exports<'locutus/php/array/array_values'>;
}
declare module 'locutus/php/array/array_walk_recursive.js' {
  declare module.exports: $Exports<'locutus/php/array/array_walk_recursive'>;
}
declare module 'locutus/php/array/array_walk.js' {
  declare module.exports: $Exports<'locutus/php/array/array_walk'>;
}
declare module 'locutus/php/array/arsort.js' {
  declare module.exports: $Exports<'locutus/php/array/arsort'>;
}
declare module 'locutus/php/array/asort.js' {
  declare module.exports: $Exports<'locutus/php/array/asort'>;
}
declare module 'locutus/php/array/count.js' {
  declare module.exports: $Exports<'locutus/php/array/count'>;
}
declare module 'locutus/php/array/current.js' {
  declare module.exports: $Exports<'locutus/php/array/current'>;
}
declare module 'locutus/php/array/each.js' {
  declare module.exports: $Exports<'locutus/php/array/each'>;
}
declare module 'locutus/php/array/end.js' {
  declare module.exports: $Exports<'locutus/php/array/end'>;
}
declare module 'locutus/php/array/in_array.js' {
  declare module.exports: $Exports<'locutus/php/array/in_array'>;
}
declare module 'locutus/php/array/index.js' {
  declare module.exports: $Exports<'locutus/php/array/index'>;
}
declare module 'locutus/php/array/key.js' {
  declare module.exports: $Exports<'locutus/php/array/key'>;
}
declare module 'locutus/php/array/krsort.js' {
  declare module.exports: $Exports<'locutus/php/array/krsort'>;
}
declare module 'locutus/php/array/ksort.js' {
  declare module.exports: $Exports<'locutus/php/array/ksort'>;
}
declare module 'locutus/php/array/natcasesort.js' {
  declare module.exports: $Exports<'locutus/php/array/natcasesort'>;
}
declare module 'locutus/php/array/natsort.js' {
  declare module.exports: $Exports<'locutus/php/array/natsort'>;
}
declare module 'locutus/php/array/next.js' {
  declare module.exports: $Exports<'locutus/php/array/next'>;
}
declare module 'locutus/php/array/pos.js' {
  declare module.exports: $Exports<'locutus/php/array/pos'>;
}
declare module 'locutus/php/array/prev.js' {
  declare module.exports: $Exports<'locutus/php/array/prev'>;
}
declare module 'locutus/php/array/range.js' {
  declare module.exports: $Exports<'locutus/php/array/range'>;
}
declare module 'locutus/php/array/reset.js' {
  declare module.exports: $Exports<'locutus/php/array/reset'>;
}
declare module 'locutus/php/array/rsort.js' {
  declare module.exports: $Exports<'locutus/php/array/rsort'>;
}
declare module 'locutus/php/array/shuffle.js' {
  declare module.exports: $Exports<'locutus/php/array/shuffle'>;
}
declare module 'locutus/php/array/sizeof.js' {
  declare module.exports: $Exports<'locutus/php/array/sizeof'>;
}
declare module 'locutus/php/array/sort.js' {
  declare module.exports: $Exports<'locutus/php/array/sort'>;
}
declare module 'locutus/php/array/uasort.js' {
  declare module.exports: $Exports<'locutus/php/array/uasort'>;
}
declare module 'locutus/php/array/uksort.js' {
  declare module.exports: $Exports<'locutus/php/array/uksort'>;
}
declare module 'locutus/php/array/usort.js' {
  declare module.exports: $Exports<'locutus/php/array/usort'>;
}
declare module 'locutus/php/bc/bcadd.js' {
  declare module.exports: $Exports<'locutus/php/bc/bcadd'>;
}
declare module 'locutus/php/bc/bccomp.js' {
  declare module.exports: $Exports<'locutus/php/bc/bccomp'>;
}
declare module 'locutus/php/bc/bcdiv.js' {
  declare module.exports: $Exports<'locutus/php/bc/bcdiv'>;
}
declare module 'locutus/php/bc/bcmul.js' {
  declare module.exports: $Exports<'locutus/php/bc/bcmul'>;
}
declare module 'locutus/php/bc/bcround.js' {
  declare module.exports: $Exports<'locutus/php/bc/bcround'>;
}
declare module 'locutus/php/bc/bcscale.js' {
  declare module.exports: $Exports<'locutus/php/bc/bcscale'>;
}
declare module 'locutus/php/bc/bcsub.js' {
  declare module.exports: $Exports<'locutus/php/bc/bcsub'>;
}
declare module 'locutus/php/bc/index.js' {
  declare module.exports: $Exports<'locutus/php/bc/index'>;
}
declare module 'locutus/php/ctype/ctype_alnum.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_alnum'>;
}
declare module 'locutus/php/ctype/ctype_alpha.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_alpha'>;
}
declare module 'locutus/php/ctype/ctype_cntrl.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_cntrl'>;
}
declare module 'locutus/php/ctype/ctype_digit.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_digit'>;
}
declare module 'locutus/php/ctype/ctype_graph.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_graph'>;
}
declare module 'locutus/php/ctype/ctype_lower.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_lower'>;
}
declare module 'locutus/php/ctype/ctype_print.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_print'>;
}
declare module 'locutus/php/ctype/ctype_punct.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_punct'>;
}
declare module 'locutus/php/ctype/ctype_space.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_space'>;
}
declare module 'locutus/php/ctype/ctype_upper.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_upper'>;
}
declare module 'locutus/php/ctype/ctype_xdigit.js' {
  declare module.exports: $Exports<'locutus/php/ctype/ctype_xdigit'>;
}
declare module 'locutus/php/ctype/index.js' {
  declare module.exports: $Exports<'locutus/php/ctype/index'>;
}
declare module 'locutus/php/datetime/checkdate.js' {
  declare module.exports: $Exports<'locutus/php/datetime/checkdate'>;
}
declare module 'locutus/php/datetime/date_parse.js' {
  declare module.exports: $Exports<'locutus/php/datetime/date_parse'>;
}
declare module 'locutus/php/datetime/date.js' {
  declare module.exports: $Exports<'locutus/php/datetime/date'>;
}
declare module 'locutus/php/datetime/getdate.js' {
  declare module.exports: $Exports<'locutus/php/datetime/getdate'>;
}
declare module 'locutus/php/datetime/gettimeofday.js' {
  declare module.exports: $Exports<'locutus/php/datetime/gettimeofday'>;
}
declare module 'locutus/php/datetime/gmdate.js' {
  declare module.exports: $Exports<'locutus/php/datetime/gmdate'>;
}
declare module 'locutus/php/datetime/gmmktime.js' {
  declare module.exports: $Exports<'locutus/php/datetime/gmmktime'>;
}
declare module 'locutus/php/datetime/gmstrftime.js' {
  declare module.exports: $Exports<'locutus/php/datetime/gmstrftime'>;
}
declare module 'locutus/php/datetime/idate.js' {
  declare module.exports: $Exports<'locutus/php/datetime/idate'>;
}
declare module 'locutus/php/datetime/index.js' {
  declare module.exports: $Exports<'locutus/php/datetime/index'>;
}
declare module 'locutus/php/datetime/microtime.js' {
  declare module.exports: $Exports<'locutus/php/datetime/microtime'>;
}
declare module 'locutus/php/datetime/mktime.js' {
  declare module.exports: $Exports<'locutus/php/datetime/mktime'>;
}
declare module 'locutus/php/datetime/strftime.js' {
  declare module.exports: $Exports<'locutus/php/datetime/strftime'>;
}
declare module 'locutus/php/datetime/strptime.js' {
  declare module.exports: $Exports<'locutus/php/datetime/strptime'>;
}
declare module 'locutus/php/datetime/strtotime.js' {
  declare module.exports: $Exports<'locutus/php/datetime/strtotime'>;
}
declare module 'locutus/php/datetime/time.js' {
  declare module.exports: $Exports<'locutus/php/datetime/time'>;
}
declare module 'locutus/php/exec/escapeshellarg.js' {
  declare module.exports: $Exports<'locutus/php/exec/escapeshellarg'>;
}
declare module 'locutus/php/exec/index.js' {
  declare module.exports: $Exports<'locutus/php/exec/index'>;
}
declare module 'locutus/php/filesystem/basename.js' {
  declare module.exports: $Exports<'locutus/php/filesystem/basename'>;
}
declare module 'locutus/php/filesystem/dirname.js' {
  declare module.exports: $Exports<'locutus/php/filesystem/dirname'>;
}
declare module 'locutus/php/filesystem/file_get_contents.js' {
  declare module.exports: $Exports<'locutus/php/filesystem/file_get_contents'>;
}
declare module 'locutus/php/filesystem/index.js' {
  declare module.exports: $Exports<'locutus/php/filesystem/index'>;
}
declare module 'locutus/php/filesystem/pathinfo.js' {
  declare module.exports: $Exports<'locutus/php/filesystem/pathinfo'>;
}
declare module 'locutus/php/filesystem/realpath.js' {
  declare module.exports: $Exports<'locutus/php/filesystem/realpath'>;
}
declare module 'locutus/php/funchand/call_user_func_array.js' {
  declare module.exports: $Exports<'locutus/php/funchand/call_user_func_array'>;
}
declare module 'locutus/php/funchand/call_user_func.js' {
  declare module.exports: $Exports<'locutus/php/funchand/call_user_func'>;
}
declare module 'locutus/php/funchand/create_function.js' {
  declare module.exports: $Exports<'locutus/php/funchand/create_function'>;
}
declare module 'locutus/php/funchand/function_exists.js' {
  declare module.exports: $Exports<'locutus/php/funchand/function_exists'>;
}
declare module 'locutus/php/funchand/get_defined_functions.js' {
  declare module.exports: $Exports<'locutus/php/funchand/get_defined_functions'>;
}
declare module 'locutus/php/funchand/index.js' {
  declare module.exports: $Exports<'locutus/php/funchand/index'>;
}
declare module 'locutus/php/i18n/i18n_loc_get_default.js' {
  declare module.exports: $Exports<'locutus/php/i18n/i18n_loc_get_default'>;
}
declare module 'locutus/php/i18n/i18n_loc_set_default.js' {
  declare module.exports: $Exports<'locutus/php/i18n/i18n_loc_set_default'>;
}
declare module 'locutus/php/i18n/index.js' {
  declare module.exports: $Exports<'locutus/php/i18n/index'>;
}
declare module 'locutus/php/index.js' {
  declare module.exports: $Exports<'locutus/php/index'>;
}
declare module 'locutus/php/info/assert_options.js' {
  declare module.exports: $Exports<'locutus/php/info/assert_options'>;
}
declare module 'locutus/php/info/getenv.js' {
  declare module.exports: $Exports<'locutus/php/info/getenv'>;
}
declare module 'locutus/php/info/index.js' {
  declare module.exports: $Exports<'locutus/php/info/index'>;
}
declare module 'locutus/php/info/ini_get.js' {
  declare module.exports: $Exports<'locutus/php/info/ini_get'>;
}
declare module 'locutus/php/info/ini_set.js' {
  declare module.exports: $Exports<'locutus/php/info/ini_set'>;
}
declare module 'locutus/php/info/set_time_limit.js' {
  declare module.exports: $Exports<'locutus/php/info/set_time_limit'>;
}
declare module 'locutus/php/info/version_compare.js' {
  declare module.exports: $Exports<'locutus/php/info/version_compare'>;
}
declare module 'locutus/php/json/index.js' {
  declare module.exports: $Exports<'locutus/php/json/index'>;
}
declare module 'locutus/php/json/json_decode.js' {
  declare module.exports: $Exports<'locutus/php/json/json_decode'>;
}
declare module 'locutus/php/json/json_encode.js' {
  declare module.exports: $Exports<'locutus/php/json/json_encode'>;
}
declare module 'locutus/php/json/json_last_error.js' {
  declare module.exports: $Exports<'locutus/php/json/json_last_error'>;
}
declare module 'locutus/php/math/abs.js' {
  declare module.exports: $Exports<'locutus/php/math/abs'>;
}
declare module 'locutus/php/math/acos.js' {
  declare module.exports: $Exports<'locutus/php/math/acos'>;
}
declare module 'locutus/php/math/acosh.js' {
  declare module.exports: $Exports<'locutus/php/math/acosh'>;
}
declare module 'locutus/php/math/asin.js' {
  declare module.exports: $Exports<'locutus/php/math/asin'>;
}
declare module 'locutus/php/math/asinh.js' {
  declare module.exports: $Exports<'locutus/php/math/asinh'>;
}
declare module 'locutus/php/math/atan.js' {
  declare module.exports: $Exports<'locutus/php/math/atan'>;
}
declare module 'locutus/php/math/atan2.js' {
  declare module.exports: $Exports<'locutus/php/math/atan2'>;
}
declare module 'locutus/php/math/atanh.js' {
  declare module.exports: $Exports<'locutus/php/math/atanh'>;
}
declare module 'locutus/php/math/base_convert.js' {
  declare module.exports: $Exports<'locutus/php/math/base_convert'>;
}
declare module 'locutus/php/math/bindec.js' {
  declare module.exports: $Exports<'locutus/php/math/bindec'>;
}
declare module 'locutus/php/math/ceil.js' {
  declare module.exports: $Exports<'locutus/php/math/ceil'>;
}
declare module 'locutus/php/math/cos.js' {
  declare module.exports: $Exports<'locutus/php/math/cos'>;
}
declare module 'locutus/php/math/cosh.js' {
  declare module.exports: $Exports<'locutus/php/math/cosh'>;
}
declare module 'locutus/php/math/decbin.js' {
  declare module.exports: $Exports<'locutus/php/math/decbin'>;
}
declare module 'locutus/php/math/dechex.js' {
  declare module.exports: $Exports<'locutus/php/math/dechex'>;
}
declare module 'locutus/php/math/decoct.js' {
  declare module.exports: $Exports<'locutus/php/math/decoct'>;
}
declare module 'locutus/php/math/deg2rad.js' {
  declare module.exports: $Exports<'locutus/php/math/deg2rad'>;
}
declare module 'locutus/php/math/exp.js' {
  declare module.exports: $Exports<'locutus/php/math/exp'>;
}
declare module 'locutus/php/math/expm1.js' {
  declare module.exports: $Exports<'locutus/php/math/expm1'>;
}
declare module 'locutus/php/math/floor.js' {
  declare module.exports: $Exports<'locutus/php/math/floor'>;
}
declare module 'locutus/php/math/fmod.js' {
  declare module.exports: $Exports<'locutus/php/math/fmod'>;
}
declare module 'locutus/php/math/getrandmax.js' {
  declare module.exports: $Exports<'locutus/php/math/getrandmax'>;
}
declare module 'locutus/php/math/hexdec.js' {
  declare module.exports: $Exports<'locutus/php/math/hexdec'>;
}
declare module 'locutus/php/math/hypot.js' {
  declare module.exports: $Exports<'locutus/php/math/hypot'>;
}
declare module 'locutus/php/math/index.js' {
  declare module.exports: $Exports<'locutus/php/math/index'>;
}
declare module 'locutus/php/math/is_finite.js' {
  declare module.exports: $Exports<'locutus/php/math/is_finite'>;
}
declare module 'locutus/php/math/is_infinite.js' {
  declare module.exports: $Exports<'locutus/php/math/is_infinite'>;
}
declare module 'locutus/php/math/is_nan.js' {
  declare module.exports: $Exports<'locutus/php/math/is_nan'>;
}
declare module 'locutus/php/math/lcg_value.js' {
  declare module.exports: $Exports<'locutus/php/math/lcg_value'>;
}
declare module 'locutus/php/math/log.js' {
  declare module.exports: $Exports<'locutus/php/math/log'>;
}
declare module 'locutus/php/math/log10.js' {
  declare module.exports: $Exports<'locutus/php/math/log10'>;
}
declare module 'locutus/php/math/log1p.js' {
  declare module.exports: $Exports<'locutus/php/math/log1p'>;
}
declare module 'locutus/php/math/max.js' {
  declare module.exports: $Exports<'locutus/php/math/max'>;
}
declare module 'locutus/php/math/min.js' {
  declare module.exports: $Exports<'locutus/php/math/min'>;
}
declare module 'locutus/php/math/mt_getrandmax.js' {
  declare module.exports: $Exports<'locutus/php/math/mt_getrandmax'>;
}
declare module 'locutus/php/math/mt_rand.js' {
  declare module.exports: $Exports<'locutus/php/math/mt_rand'>;
}
declare module 'locutus/php/math/octdec.js' {
  declare module.exports: $Exports<'locutus/php/math/octdec'>;
}
declare module 'locutus/php/math/pi.js' {
  declare module.exports: $Exports<'locutus/php/math/pi'>;
}
declare module 'locutus/php/math/pow.js' {
  declare module.exports: $Exports<'locutus/php/math/pow'>;
}
declare module 'locutus/php/math/rad2deg.js' {
  declare module.exports: $Exports<'locutus/php/math/rad2deg'>;
}
declare module 'locutus/php/math/rand.js' {
  declare module.exports: $Exports<'locutus/php/math/rand'>;
}
declare module 'locutus/php/math/round.js' {
  declare module.exports: $Exports<'locutus/php/math/round'>;
}
declare module 'locutus/php/math/sin.js' {
  declare module.exports: $Exports<'locutus/php/math/sin'>;
}
declare module 'locutus/php/math/sinh.js' {
  declare module.exports: $Exports<'locutus/php/math/sinh'>;
}
declare module 'locutus/php/math/sqrt.js' {
  declare module.exports: $Exports<'locutus/php/math/sqrt'>;
}
declare module 'locutus/php/math/tan.js' {
  declare module.exports: $Exports<'locutus/php/math/tan'>;
}
declare module 'locutus/php/math/tanh.js' {
  declare module.exports: $Exports<'locutus/php/math/tanh'>;
}
declare module 'locutus/php/misc/index.js' {
  declare module.exports: $Exports<'locutus/php/misc/index'>;
}
declare module 'locutus/php/misc/pack.js' {
  declare module.exports: $Exports<'locutus/php/misc/pack'>;
}
declare module 'locutus/php/misc/uniqid.js' {
  declare module.exports: $Exports<'locutus/php/misc/uniqid'>;
}
declare module 'locutus/php/net-gopher/gopher_parsedir.js' {
  declare module.exports: $Exports<'locutus/php/net-gopher/gopher_parsedir'>;
}
declare module 'locutus/php/net-gopher/index.js' {
  declare module.exports: $Exports<'locutus/php/net-gopher/index'>;
}
declare module 'locutus/php/network/index.js' {
  declare module.exports: $Exports<'locutus/php/network/index'>;
}
declare module 'locutus/php/network/inet_ntop.js' {
  declare module.exports: $Exports<'locutus/php/network/inet_ntop'>;
}
declare module 'locutus/php/network/inet_pton.js' {
  declare module.exports: $Exports<'locutus/php/network/inet_pton'>;
}
declare module 'locutus/php/network/ip2long.js' {
  declare module.exports: $Exports<'locutus/php/network/ip2long'>;
}
declare module 'locutus/php/network/long2ip.js' {
  declare module.exports: $Exports<'locutus/php/network/long2ip'>;
}
declare module 'locutus/php/network/setcookie.js' {
  declare module.exports: $Exports<'locutus/php/network/setcookie'>;
}
declare module 'locutus/php/network/setrawcookie.js' {
  declare module.exports: $Exports<'locutus/php/network/setrawcookie'>;
}
declare module 'locutus/php/pcre/index.js' {
  declare module.exports: $Exports<'locutus/php/pcre/index'>;
}
declare module 'locutus/php/pcre/preg_quote.js' {
  declare module.exports: $Exports<'locutus/php/pcre/preg_quote'>;
}
declare module 'locutus/php/pcre/sql_regcase.js' {
  declare module.exports: $Exports<'locutus/php/pcre/sql_regcase'>;
}
declare module 'locutus/php/strings/addcslashes.js' {
  declare module.exports: $Exports<'locutus/php/strings/addcslashes'>;
}
declare module 'locutus/php/strings/addslashes.js' {
  declare module.exports: $Exports<'locutus/php/strings/addslashes'>;
}
declare module 'locutus/php/strings/bin2hex.js' {
  declare module.exports: $Exports<'locutus/php/strings/bin2hex'>;
}
declare module 'locutus/php/strings/chop.js' {
  declare module.exports: $Exports<'locutus/php/strings/chop'>;
}
declare module 'locutus/php/strings/chr.js' {
  declare module.exports: $Exports<'locutus/php/strings/chr'>;
}
declare module 'locutus/php/strings/chunk_split.js' {
  declare module.exports: $Exports<'locutus/php/strings/chunk_split'>;
}
declare module 'locutus/php/strings/convert_cyr_string.js' {
  declare module.exports: $Exports<'locutus/php/strings/convert_cyr_string'>;
}
declare module 'locutus/php/strings/convert_uuencode.js' {
  declare module.exports: $Exports<'locutus/php/strings/convert_uuencode'>;
}
declare module 'locutus/php/strings/count_chars.js' {
  declare module.exports: $Exports<'locutus/php/strings/count_chars'>;
}
declare module 'locutus/php/strings/crc32.js' {
  declare module.exports: $Exports<'locutus/php/strings/crc32'>;
}
declare module 'locutus/php/strings/echo.js' {
  declare module.exports: $Exports<'locutus/php/strings/echo'>;
}
declare module 'locutus/php/strings/explode.js' {
  declare module.exports: $Exports<'locutus/php/strings/explode'>;
}
declare module 'locutus/php/strings/get_html_translation_table.js' {
  declare module.exports: $Exports<'locutus/php/strings/get_html_translation_table'>;
}
declare module 'locutus/php/strings/hex2bin.js' {
  declare module.exports: $Exports<'locutus/php/strings/hex2bin'>;
}
declare module 'locutus/php/strings/html_entity_decode.js' {
  declare module.exports: $Exports<'locutus/php/strings/html_entity_decode'>;
}
declare module 'locutus/php/strings/htmlentities.js' {
  declare module.exports: $Exports<'locutus/php/strings/htmlentities'>;
}
declare module 'locutus/php/strings/htmlspecialchars_decode.js' {
  declare module.exports: $Exports<'locutus/php/strings/htmlspecialchars_decode'>;
}
declare module 'locutus/php/strings/htmlspecialchars.js' {
  declare module.exports: $Exports<'locutus/php/strings/htmlspecialchars'>;
}
declare module 'locutus/php/strings/implode.js' {
  declare module.exports: $Exports<'locutus/php/strings/implode'>;
}
declare module 'locutus/php/strings/index.js' {
  declare module.exports: $Exports<'locutus/php/strings/index'>;
}
declare module 'locutus/php/strings/join.js' {
  declare module.exports: $Exports<'locutus/php/strings/join'>;
}
declare module 'locutus/php/strings/lcfirst.js' {
  declare module.exports: $Exports<'locutus/php/strings/lcfirst'>;
}
declare module 'locutus/php/strings/levenshtein.js' {
  declare module.exports: $Exports<'locutus/php/strings/levenshtein'>;
}
declare module 'locutus/php/strings/localeconv.js' {
  declare module.exports: $Exports<'locutus/php/strings/localeconv'>;
}
declare module 'locutus/php/strings/ltrim.js' {
  declare module.exports: $Exports<'locutus/php/strings/ltrim'>;
}
declare module 'locutus/php/strings/md5_file.js' {
  declare module.exports: $Exports<'locutus/php/strings/md5_file'>;
}
declare module 'locutus/php/strings/md5.js' {
  declare module.exports: $Exports<'locutus/php/strings/md5'>;
}
declare module 'locutus/php/strings/metaphone.js' {
  declare module.exports: $Exports<'locutus/php/strings/metaphone'>;
}
declare module 'locutus/php/strings/money_format.js' {
  declare module.exports: $Exports<'locutus/php/strings/money_format'>;
}
declare module 'locutus/php/strings/nl_langinfo.js' {
  declare module.exports: $Exports<'locutus/php/strings/nl_langinfo'>;
}
declare module 'locutus/php/strings/nl2br.js' {
  declare module.exports: $Exports<'locutus/php/strings/nl2br'>;
}
declare module 'locutus/php/strings/number_format.js' {
  declare module.exports: $Exports<'locutus/php/strings/number_format'>;
}
declare module 'locutus/php/strings/ord.js' {
  declare module.exports: $Exports<'locutus/php/strings/ord'>;
}
declare module 'locutus/php/strings/parse_str.js' {
  declare module.exports: $Exports<'locutus/php/strings/parse_str'>;
}
declare module 'locutus/php/strings/printf.js' {
  declare module.exports: $Exports<'locutus/php/strings/printf'>;
}
declare module 'locutus/php/strings/quoted_printable_decode.js' {
  declare module.exports: $Exports<'locutus/php/strings/quoted_printable_decode'>;
}
declare module 'locutus/php/strings/quoted_printable_encode.js' {
  declare module.exports: $Exports<'locutus/php/strings/quoted_printable_encode'>;
}
declare module 'locutus/php/strings/quotemeta.js' {
  declare module.exports: $Exports<'locutus/php/strings/quotemeta'>;
}
declare module 'locutus/php/strings/rtrim.js' {
  declare module.exports: $Exports<'locutus/php/strings/rtrim'>;
}
declare module 'locutus/php/strings/setlocale.js' {
  declare module.exports: $Exports<'locutus/php/strings/setlocale'>;
}
declare module 'locutus/php/strings/sha1_file.js' {
  declare module.exports: $Exports<'locutus/php/strings/sha1_file'>;
}
declare module 'locutus/php/strings/sha1.js' {
  declare module.exports: $Exports<'locutus/php/strings/sha1'>;
}
declare module 'locutus/php/strings/similar_text.js' {
  declare module.exports: $Exports<'locutus/php/strings/similar_text'>;
}
declare module 'locutus/php/strings/soundex.js' {
  declare module.exports: $Exports<'locutus/php/strings/soundex'>;
}
declare module 'locutus/php/strings/split.js' {
  declare module.exports: $Exports<'locutus/php/strings/split'>;
}
declare module 'locutus/php/strings/sprintf.js' {
  declare module.exports: $Exports<'locutus/php/strings/sprintf'>;
}
declare module 'locutus/php/strings/sscanf.js' {
  declare module.exports: $Exports<'locutus/php/strings/sscanf'>;
}
declare module 'locutus/php/strings/str_getcsv.js' {
  declare module.exports: $Exports<'locutus/php/strings/str_getcsv'>;
}
declare module 'locutus/php/strings/str_ireplace.js' {
  declare module.exports: $Exports<'locutus/php/strings/str_ireplace'>;
}
declare module 'locutus/php/strings/str_pad.js' {
  declare module.exports: $Exports<'locutus/php/strings/str_pad'>;
}
declare module 'locutus/php/strings/str_repeat.js' {
  declare module.exports: $Exports<'locutus/php/strings/str_repeat'>;
}
declare module 'locutus/php/strings/str_replace.js' {
  declare module.exports: $Exports<'locutus/php/strings/str_replace'>;
}
declare module 'locutus/php/strings/str_rot13.js' {
  declare module.exports: $Exports<'locutus/php/strings/str_rot13'>;
}
declare module 'locutus/php/strings/str_shuffle.js' {
  declare module.exports: $Exports<'locutus/php/strings/str_shuffle'>;
}
declare module 'locutus/php/strings/str_split.js' {
  declare module.exports: $Exports<'locutus/php/strings/str_split'>;
}
declare module 'locutus/php/strings/str_word_count.js' {
  declare module.exports: $Exports<'locutus/php/strings/str_word_count'>;
}
declare module 'locutus/php/strings/strcasecmp.js' {
  declare module.exports: $Exports<'locutus/php/strings/strcasecmp'>;
}
declare module 'locutus/php/strings/strchr.js' {
  declare module.exports: $Exports<'locutus/php/strings/strchr'>;
}
declare module 'locutus/php/strings/strcmp.js' {
  declare module.exports: $Exports<'locutus/php/strings/strcmp'>;
}
declare module 'locutus/php/strings/strcoll.js' {
  declare module.exports: $Exports<'locutus/php/strings/strcoll'>;
}
declare module 'locutus/php/strings/strcspn.js' {
  declare module.exports: $Exports<'locutus/php/strings/strcspn'>;
}
declare module 'locutus/php/strings/strip_tags.js' {
  declare module.exports: $Exports<'locutus/php/strings/strip_tags'>;
}
declare module 'locutus/php/strings/stripos.js' {
  declare module.exports: $Exports<'locutus/php/strings/stripos'>;
}
declare module 'locutus/php/strings/stripslashes.js' {
  declare module.exports: $Exports<'locutus/php/strings/stripslashes'>;
}
declare module 'locutus/php/strings/stristr.js' {
  declare module.exports: $Exports<'locutus/php/strings/stristr'>;
}
declare module 'locutus/php/strings/strlen.js' {
  declare module.exports: $Exports<'locutus/php/strings/strlen'>;
}
declare module 'locutus/php/strings/strnatcasecmp.js' {
  declare module.exports: $Exports<'locutus/php/strings/strnatcasecmp'>;
}
declare module 'locutus/php/strings/strnatcmp.js' {
  declare module.exports: $Exports<'locutus/php/strings/strnatcmp'>;
}
declare module 'locutus/php/strings/strncasecmp.js' {
  declare module.exports: $Exports<'locutus/php/strings/strncasecmp'>;
}
declare module 'locutus/php/strings/strncmp.js' {
  declare module.exports: $Exports<'locutus/php/strings/strncmp'>;
}
declare module 'locutus/php/strings/strpbrk.js' {
  declare module.exports: $Exports<'locutus/php/strings/strpbrk'>;
}
declare module 'locutus/php/strings/strpos.js' {
  declare module.exports: $Exports<'locutus/php/strings/strpos'>;
}
declare module 'locutus/php/strings/strrchr.js' {
  declare module.exports: $Exports<'locutus/php/strings/strrchr'>;
}
declare module 'locutus/php/strings/strrev.js' {
  declare module.exports: $Exports<'locutus/php/strings/strrev'>;
}
declare module 'locutus/php/strings/strripos.js' {
  declare module.exports: $Exports<'locutus/php/strings/strripos'>;
}
declare module 'locutus/php/strings/strrpos.js' {
  declare module.exports: $Exports<'locutus/php/strings/strrpos'>;
}
declare module 'locutus/php/strings/strspn.js' {
  declare module.exports: $Exports<'locutus/php/strings/strspn'>;
}
declare module 'locutus/php/strings/strstr.js' {
  declare module.exports: $Exports<'locutus/php/strings/strstr'>;
}
declare module 'locutus/php/strings/strtok.js' {
  declare module.exports: $Exports<'locutus/php/strings/strtok'>;
}
declare module 'locutus/php/strings/strtolower.js' {
  declare module.exports: $Exports<'locutus/php/strings/strtolower'>;
}
declare module 'locutus/php/strings/strtoupper.js' {
  declare module.exports: $Exports<'locutus/php/strings/strtoupper'>;
}
declare module 'locutus/php/strings/strtr.js' {
  declare module.exports: $Exports<'locutus/php/strings/strtr'>;
}
declare module 'locutus/php/strings/substr_compare.js' {
  declare module.exports: $Exports<'locutus/php/strings/substr_compare'>;
}
declare module 'locutus/php/strings/substr_count.js' {
  declare module.exports: $Exports<'locutus/php/strings/substr_count'>;
}
declare module 'locutus/php/strings/substr_replace.js' {
  declare module.exports: $Exports<'locutus/php/strings/substr_replace'>;
}
declare module 'locutus/php/strings/substr.js' {
  declare module.exports: $Exports<'locutus/php/strings/substr'>;
}
declare module 'locutus/php/strings/trim.js' {
  declare module.exports: $Exports<'locutus/php/strings/trim'>;
}
declare module 'locutus/php/strings/ucfirst.js' {
  declare module.exports: $Exports<'locutus/php/strings/ucfirst'>;
}
declare module 'locutus/php/strings/ucwords.js' {
  declare module.exports: $Exports<'locutus/php/strings/ucwords'>;
}
declare module 'locutus/php/strings/vprintf.js' {
  declare module.exports: $Exports<'locutus/php/strings/vprintf'>;
}
declare module 'locutus/php/strings/vsprintf.js' {
  declare module.exports: $Exports<'locutus/php/strings/vsprintf'>;
}
declare module 'locutus/php/strings/wordwrap.js' {
  declare module.exports: $Exports<'locutus/php/strings/wordwrap'>;
}
declare module 'locutus/php/url/base64_decode.js' {
  declare module.exports: $Exports<'locutus/php/url/base64_decode'>;
}
declare module 'locutus/php/url/base64_encode.js' {
  declare module.exports: $Exports<'locutus/php/url/base64_encode'>;
}
declare module 'locutus/php/url/http_build_query.js' {
  declare module.exports: $Exports<'locutus/php/url/http_build_query'>;
}
declare module 'locutus/php/url/index.js' {
  declare module.exports: $Exports<'locutus/php/url/index'>;
}
declare module 'locutus/php/url/parse_url.js' {
  declare module.exports: $Exports<'locutus/php/url/parse_url'>;
}
declare module 'locutus/php/url/rawurldecode.js' {
  declare module.exports: $Exports<'locutus/php/url/rawurldecode'>;
}
declare module 'locutus/php/url/rawurlencode.js' {
  declare module.exports: $Exports<'locutus/php/url/rawurlencode'>;
}
declare module 'locutus/php/url/urldecode.js' {
  declare module.exports: $Exports<'locutus/php/url/urldecode'>;
}
declare module 'locutus/php/url/urlencode.js' {
  declare module.exports: $Exports<'locutus/php/url/urlencode'>;
}
declare module 'locutus/php/var/boolval.js' {
  declare module.exports: $Exports<'locutus/php/var/boolval'>;
}
declare module 'locutus/php/var/doubleval.js' {
  declare module.exports: $Exports<'locutus/php/var/doubleval'>;
}
declare module 'locutus/php/var/empty.js' {
  declare module.exports: $Exports<'locutus/php/var/empty'>;
}
declare module 'locutus/php/var/floatval.js' {
  declare module.exports: $Exports<'locutus/php/var/floatval'>;
}
declare module 'locutus/php/var/gettype.js' {
  declare module.exports: $Exports<'locutus/php/var/gettype'>;
}
declare module 'locutus/php/var/index.js' {
  declare module.exports: $Exports<'locutus/php/var/index'>;
}
declare module 'locutus/php/var/intval.js' {
  declare module.exports: $Exports<'locutus/php/var/intval'>;
}
declare module 'locutus/php/var/is_array.js' {
  declare module.exports: $Exports<'locutus/php/var/is_array'>;
}
declare module 'locutus/php/var/is_binary.js' {
  declare module.exports: $Exports<'locutus/php/var/is_binary'>;
}
declare module 'locutus/php/var/is_bool.js' {
  declare module.exports: $Exports<'locutus/php/var/is_bool'>;
}
declare module 'locutus/php/var/is_buffer.js' {
  declare module.exports: $Exports<'locutus/php/var/is_buffer'>;
}
declare module 'locutus/php/var/is_callable.js' {
  declare module.exports: $Exports<'locutus/php/var/is_callable'>;
}
declare module 'locutus/php/var/is_double.js' {
  declare module.exports: $Exports<'locutus/php/var/is_double'>;
}
declare module 'locutus/php/var/is_float.js' {
  declare module.exports: $Exports<'locutus/php/var/is_float'>;
}
declare module 'locutus/php/var/is_int.js' {
  declare module.exports: $Exports<'locutus/php/var/is_int'>;
}
declare module 'locutus/php/var/is_integer.js' {
  declare module.exports: $Exports<'locutus/php/var/is_integer'>;
}
declare module 'locutus/php/var/is_long.js' {
  declare module.exports: $Exports<'locutus/php/var/is_long'>;
}
declare module 'locutus/php/var/is_null.js' {
  declare module.exports: $Exports<'locutus/php/var/is_null'>;
}
declare module 'locutus/php/var/is_numeric.js' {
  declare module.exports: $Exports<'locutus/php/var/is_numeric'>;
}
declare module 'locutus/php/var/is_object.js' {
  declare module.exports: $Exports<'locutus/php/var/is_object'>;
}
declare module 'locutus/php/var/is_real.js' {
  declare module.exports: $Exports<'locutus/php/var/is_real'>;
}
declare module 'locutus/php/var/is_scalar.js' {
  declare module.exports: $Exports<'locutus/php/var/is_scalar'>;
}
declare module 'locutus/php/var/is_string.js' {
  declare module.exports: $Exports<'locutus/php/var/is_string'>;
}
declare module 'locutus/php/var/is_unicode.js' {
  declare module.exports: $Exports<'locutus/php/var/is_unicode'>;
}
declare module 'locutus/php/var/isset.js' {
  declare module.exports: $Exports<'locutus/php/var/isset'>;
}
declare module 'locutus/php/var/print_r.js' {
  declare module.exports: $Exports<'locutus/php/var/print_r'>;
}
declare module 'locutus/php/var/serialize.js' {
  declare module.exports: $Exports<'locutus/php/var/serialize'>;
}
declare module 'locutus/php/var/strval.js' {
  declare module.exports: $Exports<'locutus/php/var/strval'>;
}
declare module 'locutus/php/var/unserialize.js' {
  declare module.exports: $Exports<'locutus/php/var/unserialize'>;
}
declare module 'locutus/php/var/var_dump.js' {
  declare module.exports: $Exports<'locutus/php/var/var_dump'>;
}
declare module 'locutus/php/var/var_export.js' {
  declare module.exports: $Exports<'locutus/php/var/var_export'>;
}
declare module 'locutus/php/xdiff/index.js' {
  declare module.exports: $Exports<'locutus/php/xdiff/index'>;
}
declare module 'locutus/php/xdiff/xdiff_string_diff.js' {
  declare module.exports: $Exports<'locutus/php/xdiff/xdiff_string_diff'>;
}
declare module 'locutus/php/xdiff/xdiff_string_patch.js' {
  declare module.exports: $Exports<'locutus/php/xdiff/xdiff_string_patch'>;
}
declare module 'locutus/php/xml/index.js' {
  declare module.exports: $Exports<'locutus/php/xml/index'>;
}
declare module 'locutus/php/xml/utf8_decode.js' {
  declare module.exports: $Exports<'locutus/php/xml/utf8_decode'>;
}
declare module 'locutus/php/xml/utf8_encode.js' {
  declare module.exports: $Exports<'locutus/php/xml/utf8_encode'>;
}
declare module 'locutus/python/index.js' {
  declare module.exports: $Exports<'locutus/python/index'>;
}
declare module 'locutus/python/string/capwords.js' {
  declare module.exports: $Exports<'locutus/python/string/capwords'>;
}
declare module 'locutus/python/string/index.js' {
  declare module.exports: $Exports<'locutus/python/string/index'>;
}
declare module 'locutus/ruby/index.js' {
  declare module.exports: $Exports<'locutus/ruby/index'>;
}
declare module 'locutus/ruby/Math/acos.js' {
  declare module.exports: $Exports<'locutus/ruby/Math/acos'>;
}
declare module 'locutus/ruby/Math/index.js' {
  declare module.exports: $Exports<'locutus/ruby/Math/index'>;
}
