// flow-typed signature: 2e19fcc1a1fc595db8045283fc7b02e0
// flow-typed version: <<STUB>>/marked_v0.6.x/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'marked'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'marked' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'marked/lib/marked' {
  declare module.exports: any;
}

declare module 'marked/marked.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'marked/lib/marked.js' {
  declare module.exports: $Exports<'marked/lib/marked'>;
}
declare module 'marked/marked.min.js' {
  declare module.exports: $Exports<'marked/marked.min'>;
}
