// flow-typed signature: 9024c52d68f35abe850da0e536865cef
// flow-typed version: <<STUB>>/selectize_v0.12.x/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'selectize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'selectize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'selectize/dist/js/selectize' {
  declare module.exports: any;
}

declare module 'selectize/dist/js/selectize.min' {
  declare module.exports: any;
}

declare module 'selectize/dist/js/standalone/selectize' {
  declare module.exports: any;
}

declare module 'selectize/dist/js/standalone/selectize.min' {
  declare module.exports: any;
}

declare module 'selectize/examples/js/es5' {
  declare module.exports: any;
}

declare module 'selectize/examples/js/index' {
  declare module.exports: any;
}

declare module 'selectize/examples/js/jquery.min' {
  declare module.exports: any;
}

declare module 'selectize/examples/js/jqueryui' {
  declare module.exports: any;
}

declare module 'selectize/Gruntfile' {
  declare module.exports: any;
}

declare module 'selectize/karma.conf' {
  declare module.exports: any;
}

declare module 'selectize/notes/i18n-feature' {
  declare module.exports: any;
}

declare module 'selectize/src/constants' {
  declare module.exports: any;
}

declare module 'selectize/src/contrib/highlight' {
  declare module.exports: any;
}

declare module 'selectize/src/contrib/microevent' {
  declare module.exports: any;
}

declare module 'selectize/src/defaults' {
  declare module.exports: any;
}

declare module 'selectize/src/plugins/drag_drop/plugin' {
  declare module.exports: any;
}

declare module 'selectize/src/plugins/dropdown_header/plugin' {
  declare module.exports: any;
}

declare module 'selectize/src/plugins/optgroup_columns/plugin' {
  declare module.exports: any;
}

declare module 'selectize/src/plugins/remove_button/plugin' {
  declare module.exports: any;
}

declare module 'selectize/src/plugins/restore_on_backspace/plugin' {
  declare module.exports: any;
}

declare module 'selectize/src/selectize.jquery' {
  declare module.exports: any;
}

declare module 'selectize/src/selectize' {
  declare module.exports: any;
}

declare module 'selectize/src/utils' {
  declare module.exports: any;
}

declare module 'selectize/test/api' {
  declare module.exports: any;
}

declare module 'selectize/test/events_dom' {
  declare module.exports: any;
}

declare module 'selectize/test/events' {
  declare module.exports: any;
}

declare module 'selectize/test/interaction' {
  declare module.exports: any;
}

declare module 'selectize/test/setup' {
  declare module.exports: any;
}

declare module 'selectize/test/support/base' {
  declare module.exports: any;
}

declare module 'selectize/test/support/syn' {
  declare module.exports: any;
}

declare module 'selectize/test/xss' {
  declare module.exports: any;
}

// Filename aliases
declare module 'selectize/dist/js/selectize.js' {
  declare module.exports: $Exports<'selectize/dist/js/selectize'>;
}
declare module 'selectize/dist/js/selectize.min.js' {
  declare module.exports: $Exports<'selectize/dist/js/selectize.min'>;
}
declare module 'selectize/dist/js/standalone/selectize.js' {
  declare module.exports: $Exports<'selectize/dist/js/standalone/selectize'>;
}
declare module 'selectize/dist/js/standalone/selectize.min.js' {
  declare module.exports: $Exports<'selectize/dist/js/standalone/selectize.min'>;
}
declare module 'selectize/examples/js/es5.js' {
  declare module.exports: $Exports<'selectize/examples/js/es5'>;
}
declare module 'selectize/examples/js/index.js' {
  declare module.exports: $Exports<'selectize/examples/js/index'>;
}
declare module 'selectize/examples/js/jquery.min.js' {
  declare module.exports: $Exports<'selectize/examples/js/jquery.min'>;
}
declare module 'selectize/examples/js/jqueryui.js' {
  declare module.exports: $Exports<'selectize/examples/js/jqueryui'>;
}
declare module 'selectize/Gruntfile.js' {
  declare module.exports: $Exports<'selectize/Gruntfile'>;
}
declare module 'selectize/karma.conf.js' {
  declare module.exports: $Exports<'selectize/karma.conf'>;
}
declare module 'selectize/notes/i18n-feature.js' {
  declare module.exports: $Exports<'selectize/notes/i18n-feature'>;
}
declare module 'selectize/src/constants.js' {
  declare module.exports: $Exports<'selectize/src/constants'>;
}
declare module 'selectize/src/contrib/highlight.js' {
  declare module.exports: $Exports<'selectize/src/contrib/highlight'>;
}
declare module 'selectize/src/contrib/microevent.js' {
  declare module.exports: $Exports<'selectize/src/contrib/microevent'>;
}
declare module 'selectize/src/defaults.js' {
  declare module.exports: $Exports<'selectize/src/defaults'>;
}
declare module 'selectize/src/plugins/drag_drop/plugin.js' {
  declare module.exports: $Exports<'selectize/src/plugins/drag_drop/plugin'>;
}
declare module 'selectize/src/plugins/dropdown_header/plugin.js' {
  declare module.exports: $Exports<'selectize/src/plugins/dropdown_header/plugin'>;
}
declare module 'selectize/src/plugins/optgroup_columns/plugin.js' {
  declare module.exports: $Exports<'selectize/src/plugins/optgroup_columns/plugin'>;
}
declare module 'selectize/src/plugins/remove_button/plugin.js' {
  declare module.exports: $Exports<'selectize/src/plugins/remove_button/plugin'>;
}
declare module 'selectize/src/plugins/restore_on_backspace/plugin.js' {
  declare module.exports: $Exports<'selectize/src/plugins/restore_on_backspace/plugin'>;
}
declare module 'selectize/src/selectize.jquery.js' {
  declare module.exports: $Exports<'selectize/src/selectize.jquery'>;
}
declare module 'selectize/src/selectize.js' {
  declare module.exports: $Exports<'selectize/src/selectize'>;
}
declare module 'selectize/src/utils.js' {
  declare module.exports: $Exports<'selectize/src/utils'>;
}
declare module 'selectize/test/api.js' {
  declare module.exports: $Exports<'selectize/test/api'>;
}
declare module 'selectize/test/events_dom.js' {
  declare module.exports: $Exports<'selectize/test/events_dom'>;
}
declare module 'selectize/test/events.js' {
  declare module.exports: $Exports<'selectize/test/events'>;
}
declare module 'selectize/test/interaction.js' {
  declare module.exports: $Exports<'selectize/test/interaction'>;
}
declare module 'selectize/test/setup.js' {
  declare module.exports: $Exports<'selectize/test/setup'>;
}
declare module 'selectize/test/support/base.js' {
  declare module.exports: $Exports<'selectize/test/support/base'>;
}
declare module 'selectize/test/support/syn.js' {
  declare module.exports: $Exports<'selectize/test/support/syn'>;
}
declare module 'selectize/test/xss.js' {
  declare module.exports: $Exports<'selectize/test/xss'>;
}
