// flow-typed signature: 578a6f76e4b5442a4241dd18c933735e
// flow-typed version: <<STUB>>/spectrum-colorpicker_v1.8.x/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spectrum-colorpicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spectrum-colorpicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spectrum-colorpicker/docs/docs' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/docs/jquery-1.9.1' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/docs/jquery-2.1.0' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/docs/prettify' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/docs/toc' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/example/example' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/Gruntfile' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-ar' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-de' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-dk' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-es' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-fa' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-fi' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-fr' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-gr' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-he' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-hr' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-id' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-it' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-ja' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-lt' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-nl' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-pl' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-pt-br' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-ru' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-sv' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-tr' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-zh-cn' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/i18n/jquery.spectrum-zh-tw' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/spectrum' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/test/loaders' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/test/qunit' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/test/require' {
  declare module.exports: any;
}

declare module 'spectrum-colorpicker/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spectrum-colorpicker/docs/docs.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/docs/docs'>;
}
declare module 'spectrum-colorpicker/docs/jquery-1.9.1.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/docs/jquery-1.9.1'>;
}
declare module 'spectrum-colorpicker/docs/jquery-2.1.0.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/docs/jquery-2.1.0'>;
}
declare module 'spectrum-colorpicker/docs/prettify.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/docs/prettify'>;
}
declare module 'spectrum-colorpicker/docs/toc.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/docs/toc'>;
}
declare module 'spectrum-colorpicker/example/example.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/example/example'>;
}
declare module 'spectrum-colorpicker/Gruntfile.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/Gruntfile'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-ar.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-ar'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-de.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-de'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-dk.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-dk'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-es.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-es'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-fa.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-fa'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-fi.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-fi'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-fr.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-fr'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-gr.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-gr'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-he.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-he'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-hr.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-hr'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-id.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-id'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-it.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-it'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-ja.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-ja'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-lt.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-lt'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-nl.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-nl'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-pl.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-pl'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-pt-br.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-pt-br'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-ru.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-ru'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-sv.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-sv'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-tr.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-tr'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-zh-cn.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-zh-cn'>;
}
declare module 'spectrum-colorpicker/i18n/jquery.spectrum-zh-tw.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/i18n/jquery.spectrum-zh-tw'>;
}
declare module 'spectrum-colorpicker/spectrum.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/spectrum'>;
}
declare module 'spectrum-colorpicker/test/loaders.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/test/loaders'>;
}
declare module 'spectrum-colorpicker/test/qunit.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/test/qunit'>;
}
declare module 'spectrum-colorpicker/test/require.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/test/require'>;
}
declare module 'spectrum-colorpicker/test/tests.js' {
  declare module.exports: $Exports<'spectrum-colorpicker/test/tests'>;
}
