// flow-typed signature: b13f792d5e45e71ef816417265e78560
// flow-typed version: <<STUB>>/@knitkode/vendor_vgithub:knitkode/vendor.git/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knitkode/vendor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knitkode/vendor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knitkode/vendor/cp/highlight.pack' {
  declare module.exports: any;
}

declare module '@knitkode/vendor/cp/modernizr-custom' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knitkode/vendor/cp/highlight.pack.js' {
  declare module.exports: $Exports<'@knitkode/vendor/cp/highlight.pack'>;
}
declare module '@knitkode/vendor/cp/modernizr-custom.js' {
  declare module.exports: $Exports<'@knitkode/vendor/cp/modernizr-custom'>;
}
